spring:
  application:
    name: spring-data-redis-example

  r2dbc:
    url: r2dbc:postgres://localhost:5432/redis-example
    username: admin
    password: password

  redis:
    host: localhost
    port: 6379
